[package]
name = "dex-router-io"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
gmeta.workspace = true
gstd.workspace = true
dex-io.workspace = true
dex-factory-io.workspace = true
dex-wvara-io.workspace = true

