[package]
name = "dex-wvara"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
gstd.workspace = true
dex-wvara-io.workspace = true

[build-dependencies]
gear-wasm-builder.workspace = true
dex-wvara-io.workspace = true
